name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  test_01sh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: chmod 01sh script
        run: chmod +x 01.sh
        
      - name: chmod analysispy script
        run: chmod +x analysis.py
        
      - name: chmod visualizationpy script
        run: chmod +x visualization.py
        
      - name: numpy
        run: pip3 install numpy
        
      - name: pandas
        run: pip3 install pandas
        
      - name: pandas
        run: pip3 install matplotlib
        
      - name: seaborn
        run: pip3 install seaborn
        
      - name: Run 01sh script
        run: ./01.sh https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data
        

